# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65xample_service.proto\"#\n\rDecodeRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"2\n\x0c\x44\x65\x63odeResult\x12\r\n\x05\x66inal\x18\x01 \x01(\x08\x12\x13\n\x0btext_result\x18\x02 \x01(\t2D\n\rStreamService\x12\x33\n\x0cStreamDecode\x12\x0e.DecodeRequest\x1a\r.DecodeResult\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DECODEREQUEST._serialized_start=25
  _DECODEREQUEST._serialized_end=60
  _DECODERESULT._serialized_start=62
  _DECODERESULT._serialized_end=112
  _STREAMSERVICE._serialized_start=114
  _STREAMSERVICE._serialized_end=182
# @@protoc_insertion_point(module_scope)
